### PR TITLE
[WIP] changes to css + init chrome support

### PR DESCRIPTION
**Pull request by BrodyHughes**
- started looking into Chrome support
- also moved to external css file and cleaned up some wording
- also used prettier to clean up the files a little

TODO:
- need to work out a couple chrome bugs
- need to figure out a good workflow for setting up chrome / ff builds separately

### CODE REVIEW

**Review by roguedex-dev — COMMENTED** [review]
I've looked at your MR, so far so good, I've implemented most of your changes on my local git repo, I will push either tonight or tomorrow as I'm reworking the UI.

**Comment by BrodyHughes** [comment]
@roguedex-dev how do u feel about migrating this project to React Native? A lot of the logic and setup would be much easier to implement

**Comment by roguedex-dev** [comment]
@BrodyHughes might be an idea, however first stay tuned because I've reworked the core logic, making it much simpler and stable. I'll push tomorrow as I'm also reworking the UI

**Comment by BrodyHughes** [comment]
I also was messing around and added a minimize feature on my local. was doing something like this if you wanted to steal:

```
mainWrapper.setAttribute('data-minimized', 'false');
  
	const handleMinimize = () => {
	  const isMinimized = mainWrapper.getAttribute('data-minimized') === 'true';
	  mainWrapper.setAttribute('data-minimized', !isMinimized);
  
	  if (isMinimized) {
		mainWrapper.className = "expanded";
		miniButton.textContent = "-";
	  } else {
		mainWrapper.className = "minimized";
		miniButton.textContent = "+";
	  }
	};
	
	const miniButton = document.createElement("div");
	miniButton.className = "mini-button";
	miniButton.textContent = "-";
	miniButton.onclick = handleMinimize; 
  
	mainWrapper.appendChild(miniButton);
```
And then for css something like:
```

.expanded {
    position: fixed;
    padding: 20px;
    z-index: 9999;
    width: 500px;
    height: fit-content;
    font-family: 'Arial', sans-serif;
    font-size: 16px;
    color: #000000;
    background-color: #F8F8F0;
    border: 3px solid #6a6a6a;
    box-shadow: 3px 3px 0px #292929;
    color: #303030; 
    text-align: left; 
    box-sizing: border-box;
    display: flex;
    align-items: center;
    justify-content: space-around;
    flex-flow: row wrap;
  }

.mini-button {
  display: flex;
  align-items: center;
  justify-content: center;
  flex-flow: row wrap;
  position: relative;
  width: 13px;
  background-color: #F8F8F0;
  border-right: 2px solid #6a6a6a;
  cursor: pointer;
  top: 5;
  left: 5;
  line-height: 0;
  padding: 2px;
  height: 100%;
  position: absolute;
  left: 0;
  min-height: 13px;
  box-shadow: none;
  height: calc(100% - 6px);
}

.minimized .mini-button {
    position: relative;
}

.main-fixed .minimized {
  height: 20px;
  width: 20px;
  position: fixed;
  display: none;
  font-size: 0;
 }
 ```
 a few other small things but i'm sure u get the gist

**Comment by BrodyHughes** [comment]
excited to see it!

**Comment by roguedex-dev** [comment]
I also had the idea of a minimize button, glad that you started working on it already, will steal if it still works with how things are going to be shown next

**Comment by roguedex-dev** [comment]
Let me know what you think of the newest version!

**Pull request closed without merging**
